site:
  description: 前事不忘后事之师
menu:
  Home: /
  Archives: /archives/
  Github: https://github.com/huoher
footermenus:
  Home: /
  Archives: /archives
  About: /about/
copyright:
  is: false
  icp: 沪ICP备00000001号
  anbei: 浙公网安备 33010602002000号
  anu: 所有权利保留 转载请联系作者
  author: Huoher. Inc

banner:
  title: 在 SegmentFault，学习技能、解决问题
  content: 每个月，我们帮助 1000 万的开发者解决各种各样的技术问题。并助力他们在技术能力、职业生涯、影响力上获得提升。

announcement:
  content: 祝各位社区开发者 2019 春节快乐！一起来聊聊你的春节都怎么过？
  url: /about
